export const TOPIC_RESEARCH_FEATURE = "topic-research";
export const DEFAULT_TOPIC_RESEARCH_MODEL = "gpt-5.6-terra";
export const DEFAULT_TOPIC_RESEARCH_MAX_OUTPUT_TOKENS = 4_000;
export const DEFAULT_TOPIC_RESEARCH_MAX_WEB_SEARCH_CALLS = 4;
export const TOPIC_RESEARCH_MAX_SOURCES = 10;
export const TOPIC_RESEARCH_MAX_SEED_SOURCES = 10;
export const TOPIC_RESEARCH_MAX_SUMMARY_LENGTH = 1_000;
